## Pandas lecture 2
1.StringIO<br>
2.Pandas read_csv

In [2]:
from io import StringIO

In [3]:
import pandas as pd
df=pd.read_csv('mercedesbenz.csv')

In [4]:
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
data=("col1,col2,col3\n"
      'p,x,1\n'
      'q,y,2\n'
      'r,z,3')

In [7]:
type(data)

str

In [8]:
# in memory file format object
StringIO(data)

In [9]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    p    x     1
1    q    y     2
2    r    z     3

In [10]:
pd.read_csv(StringIO(data),usecols=['col1','col3'])

  col1  col3
0    p     1
1    q     2
2    r     3

In [20]:
import pandas as pd
df=pd.read_csv('mercedesbenz.csv',usecols=['X0','X1','X2','X3',	'X4','X5'])
df.head()

   X0 X1  X2 X3 X4 X5
0   k  v  at  a  d  u
1   k  t  av  e  d  y
2  az  w   n  c  d  x
3  az  t   n  f  d  x
4  az  v   n  f  d  h

In [48]:
## datatypes in csv
data=('a,b,c,d\n'
        '1,2,3,4\n'
         '5,6,7,8\n'
         '9,10,11')

In [38]:
pd.read_csv(StringIO(data))

   a   b   c    d
0  1   2   3  4.0
1  5   6   7  8.0
2  9  10  11  NaN

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X0      4209 non-null   object
 1   X1      4209 non-null   object
 2   X2      4209 non-null   object
 3   X3      4209 non-null   object
 4   X4      4209 non-null   object
 5   X5      4209 non-null   object
dtypes: object(6)
memory usage: 197.4+ KB

In [46]:
df.head()

   X0 X1  X2 X3 X4 X5
0   k  v  at  a  d  u
1   k  t  av  e  d  y
2  az  w   n  c  d  x
3  az  t   n  f  d  x
4  az  v   n  f  d  h

## Pandas lecture 3
1.read json (read_json)<br>
2.to json(to_json)<br>
3.json normalize

In [10]:
import pandas as pd
df= pd.DataFrame([['a','b'],['c','d']],
                index=['row1','row2'],
                columns=['col1','col2'])

In [12]:
df

     col1 col2
row1    a    b
row2    c    d

In [14]:
df.to_json()

'{"col1":{"row1":"a","row2":"c"},"col2":{"row1":"b","row2":"d"}}'

In [16]:
df.to_json(orient='index')

'{"row1":{"col1":"a","col2":"b"},"row2":{"col1":"c","col2":"d"}}'

In [18]:
df.to_json(orient='columns')

'{"col1":{"row1":"a","row2":"c"},"col2":{"row1":"b","row2":"d"}}'

In [20]:
df.to_json(orient='records')

'[{"col1":"a","col2":"b"},{"col1":"c","col2":"d"}]'

In [22]:
df.to_json(orient='split')

'{"columns":["col1","col2"],"index":["row1","row2"],"data":[["a","b"],["c","d"]]}'